version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./:/app
